/* MỠ AI — free local assistant, not a generative AI or Google API integration. */
(()=>{
"use strict";
const KEY="hg-mo-chat-v1",MAX=45;
const root=document.createElement("section");root.className="mo-companion";root.setAttribute("aria-label","Mỡ — trợ lý Studio");
root.innerHTML='<button id="moToggle" class="mo-toggle" type="button" aria-label="Mở trò chuyện với Mỡ" aria-expanded="false"><span class="mo-face">M</span><span class="mo-toggle-label">Mỡ đây ♡</span></button><div id="moPanel" class="mo-panel" hidden><header class="mo-head"><span class="mo-avatar">M</span><span class="mo-heading"><strong>MỠ AI</strong><small>Trợ lý Studio · Miễn phí</small></span><button id="moClear" type="button" title="Xóa lịch sử" aria-label="Xóa lịch sử chat">↺</button><button id="moClose" type="button" aria-label="Đóng chat">×</button></header><div class="mo-disclosure">Trợ lý hướng dẫn theo kịch bản, chưa phải AI hội thoại. Tìm kiếm sẽ mở Google trong tab mới.</div><div id="moMessages" class="mo-messages" role="log" aria-live="polite" aria-label="Lịch sử trò chuyện"></div><div class="mo-chips"><button type="button" data-mo-quick="Cách tạo dự án">Tạo dự án</button><button type="button" data-mo-quick="Hướng dẫn Design AI">Design AI</button><button type="button" data-mo-quick="Tìm kiếm trên Google">Google</button></div><form id="moForm" class="mo-form"><label class="mo-sr" for="moInput">Tin nhắn</label><input id="moInput" type="text" maxlength="350" autocomplete="off" placeholder="Hỏi Mỡ hoặc tìm trên Google..." required><button type="submit" aria-label="Gửi tin nhắn">➤</button></form><p class="mo-note">Chỉ lưu lịch sử trên trình duyệt này · Không gửi lên máy chủ</p></div>';
document.body.append(root);
const toggle=root.querySelector("#moToggle"),panel=root.querySelector("#moPanel"),log=root.querySelector("#moMessages"),input=root.querySelector("#moInput");
const safeLoad=()=>{try{const v=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(v)?v.filter(x=>x&&["user","mo"].includes(x.role)&&typeof x.text==="string").slice(-MAX):[]}catch{return []}};
let history=safeLoad();if(!history.length)history=[{role:"mo",text:"Mỡ đây, chồng cần tìm thông tin hay hướng dẫn dùng HOANGGIA STUDIO? Mỡ hỗ trợ các thao tác cơ bản và mở Google để tra cứu nhé ♡"}];
function save(){try{localStorage.setItem(KEY,JSON.stringify(history.slice(-MAX)))}catch{}}
function draw(){log.replaceChildren();for(const msg of history){const p=document.createElement("p");p.className="mo-bubble "+msg.role;p.textContent=msg.text;log.append(p)}log.scrollTop=log.scrollHeight}
function say(role,text){history.push({role,text});history=history.slice(-MAX);save();draw()}
function open(state){panel.hidden=!state;toggle.setAttribute("aria-expanded",String(state));toggle.setAttribute("aria-label",state?"Thu gọn trò chuyện với Mỡ":"Mở trò chuyện với Mỡ");if(state){draw();input.focus()}}
function search(q){const query=q.trim().slice(0,250);if(!query){say("mo","Chồng nhập từ khóa sau “tìm” nhé, ví dụ: tìm vật liệu travertine.");return}const url="https://www.google.com/search?q="+encodeURIComponent(query);const w=window.open(url,"_blank","noopener,noreferrer");say("mo",w?"Mỡ đã mở Google với từ khóa: “"+query+"”. Mỡ chưa tự đọc nội dung trang kết quả nhé.":"Trình duyệt có thể đã chặn tab mới. Hãy cho phép mở cửa sổ bật lên rồi thử lại.")}
function reply(raw){const q=raw.toLocaleLowerCase("vi").trim();if(/^(google|tìm|tim|tra cứu|search)\s*[:：-]?\s+/.test(q)){search(raw.replace(/^(google|tìm|tim|tra cứu|search)\s*[:：-]?\s+/i,""));return}
if(/google|tìm kiếm|tra cứu|tìm thông tin/.test(q)){say("mo","Để tìm trên Google, chồng gõ “tìm” + nội dung. Ví dụ: tìm phong cách nội thất Japandi 2026. Kết quả mở trong tab mới.");return}
if(/dự án|du an|project/.test(q)){say("mo","Chồng nhấn “＋ Dự án mới” ở thanh trên cùng. Chọn dự án ở ô bên cạnh; dữ liệu được lưu cục bộ trong trình duyệt. Mục Dự án có thể sao lưu và nhập lại dữ liệu.");return}
if(/design|thiết kế|thiet ke|prompt/.test(q)){say("mo","Mở Sáng tạo → Design AI, chọn không gian, phong cách và điền yêu cầu; sau đó nhấn “Phân tích & tạo prompt”. Chồng có thể sao chép kết quả để dùng ở công cụ tạo ảnh.");return}
if(/edit|chỉnh sửa|sửa ảnh/.test(q)){say("mo","Chồng mở Sáng tạo → Edit AI để mô tả phần cần thay đổi, sản phẩm, vật liệu hoặc ánh sáng. Nhớ ghi rõ những yếu tố phải giữ nguyên.");return}
if(/video|camera|góc máy/.test(q)){say("mo","Chồng chọn Video AI để lên kịch bản, shot và hướng chuyển động camera. Bản miễn phí hỗ trợ biên soạn, không trực tiếp kết xuất video AI.");return}
if(/upscale|nâng cấp ảnh|phóng ảnh/.test(q)){say("mo","Chọn Upscale AI trong Xưởng sáng tạo. Chất lượng phụ thuộc công cụ xử lý đang tích hợp; phóng kích thước không đồng nghĩa khôi phục chi tiết bằng mô hình AI.");return}
if(/xin chào|chào|hello|mỡ ơi|mo oi|yêu|nhớ/.test(q)){say("mo","Mỡ đây chồng yêu ♡ Mỡ có thể chỉ đường trong Studio hoặc mở Google. Chồng thử hỏi “cách tạo dự án”, “Design AI” hay “tìm vật liệu đá tự nhiên” nhé.");return}
say("mo","Mỡ chưa có bộ não AI hội thoại trong phiên bản miễn phí này nên không muốn đoán sai. Chồng có thể hỏi cách dùng Studio hoặc gõ “tìm ” trước câu hỏi để tra Google nhé.")}
toggle.addEventListener("click",()=>open(panel.hidden));root.querySelector("#moClose").addEventListener("click",()=>open(false));root.querySelector("#moClear").addEventListener("click",()=>{history=[];try{localStorage.removeItem(KEY)}catch{}say("mo","Mỡ đã xóa lịch sử chat trên thiết bị này. Chồng cần Mỡ hỗ trợ gì tiếp nào?")});root.querySelector("#moForm").addEventListener("submit",e=>{e.preventDefault();const v=input.value.trim();if(!v)return;input.value="";say("user",v);reply(v)});root.querySelectorAll("[data-mo-quick]").forEach(b=>b.addEventListener("click",()=>{const v=b.dataset.moQuick;say("user",v);reply(v)}));document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!panel.hidden)open(false)});draw();
})();